### ISSUE TITLE
[QnA] How did you design the faces?

### ISSUE THREAD

**Issue by KendallDoesCoding** [virejdasani/Incredibly-InYourFace#2]
Did you use a application to design the faces?

**Comment by virejdasani** [comment]
Hey, I just used google to get the images

**Comment by KendallDoesCoding** [comment]
> Hey, I just used google to get the images

Oh, what about copyright lol

**Comment by AcrylicShrimp** [comment]
He stole this from forked one: https://github.com/ttoowa/InYourFace_incredible

Look at this commit, what a nice copy-and-paste https://github.com/virejdasani/Incredibly-InYourFace/commit/04e3bfc93277b9d3a7b542e84300c10074f01057

**Comment by KendallDoesCoding** [comment]
Virej, you should attribute the creator haha

**Comment by virejdasani** [comment]
> He stole this from forked one: https://github.com/ttoowa/InYourFace_incredible
> 
> Look at this commit, what a nice copy-and-paste [04e3bfc](https://github.com/virejdasani/Incredibly-InYourFace/commit/04e3bfc93277b9d3a7b542e84300c10074f01057)
> 
> Virej, you should attribute the creator haha


Haha that's funny considering they copied my entire project, changed 3 images, and published it to the marketplace as their own extension 👏

**Comment by AcrylicShrimp** [comment]
> > He stole this from forked one: https://github.com/ttoowa/InYourFace_incredible
> > Look at this commit, what a nice copy-and-paste [04e3bfc](https://github.com/virejdasani/Incredibly-InYourFace/commit/04e3bfc93277b9d3a7b542e84300c10074f01057)
> > Virej, you should attribute the creator haha
> 
> Haha that's funny considering they copied my entire project, changed 3 images, and published it to the marketplace as their own extension 👏

Steal? Who? Your extension is MIT LICENSED, so he just forked your project and created a new one. He wasn't steal. But how about your action? You did just copy-and-paste all of he's changes and published exactly same one. You little kid 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by virejdasani** [comment]
> > > He stole this from forked one: https://github.com/ttoowa/InYourFace_incredible
> > > Look at this commit, what a nice copy-and-paste [04e3bfc](https://github.com/virejdasani/Incredibly-InYourFace/commit/04e3bfc93277b9d3a7b542e84300c10074f01057)
> > > Virej, you should attribute the creator haha
> > 
> > 
> > Haha that's funny considering they copied my entire project, changed 3 images, and published it to the marketplace as their own extension 👏
> 
> Steal? Who? Your extension is MIT LICENSED, so he just forked your project and create a new one. He wasn't steal. But how about your action? You did just copy-and-paste all of he's changes and published exactly same one. You little kid 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯


Hey, I'm not sure if you know this but [this](https://github.com/ttoowa/InYourFace_incredible) project has an MIT LICENSE that's under my name.
Furthermore, the code for this extension is from my extension called "In Your Face".
Please get your facts straight before throwing around such wild accusations, thanks.
